---
- name: Install reddit to irc transport
  hosts: glportal
  tasks:
  - name: Create directory for irc transport
    file: path="{{ansible_env.HOME}}/system/docker/reddit-bot/" recurse=yes state=directory
  - name: Checkout transport bot
    git: repo=https://github.com/GlPortal/reddit-bot.git dest={{ansible_env.HOME}}/system/docker/reddit-bot
  - name: Run transport bot
    shell: docker-compose up -d
    args:
      chdir: "{{ansible_env.HOME}}/system/docker/reddit-bot/"
